#!/usr/bin/env sh

# Detect which package manager to use
if [ -f "yarn.lock" ]; then
  yarn lint && yarn build
elif [ -f "package-lock.json" ]; then
  npm run lint && npm run build
else
  pnpm lint && pnpm build
fi
